# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install Gtk
      run: sudo apt-get update && sudo apt-get install -y libgirepository1.0-dev gir1.2-gtk-3.0 libgtk-3-dev gir1.2-pango-1.0 libpango1.0-dev gir1.2-gtksource-4 libgtksourceview-4-dev libicu-dev gir1.2-webkit2-4.0 libwebkit2gtk-4.0-dev graphviz libssl-dev libffi-dev libsqlite3-dev libxml2-dev git
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel
    - name: Install dependencies
      run: |
        pipenv install
    - name: Core unittests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: |
          pipenv run nosetests -A "not moth and not internet and not fails and not git and not gui and not suspect and not integration" -w ./w3af/

    name: Test w3af
